server:
  port: 1111
eureka:
  instance:
    hostname: localhost
spring:
  application:
     name: APIGATEWAY-SERVICE
  cloud:
    gateway:
      routes:
      - id: 
        uri: http://localhost:8084/
        predicates:
        - Path=/admin/**
      - id: 
        uri: http://localhost:8083/
        predicates:
        - Path=/customer/**
      - id: 
        uri: http://localhost:8082/
        predicates:
        - Path=/order/**
      - id: 
        uri: http://localhost:8081/
        predicates:
        - Path=/product/**
      - id: 
        uri: http://localhost:8085/
        predicates:
        - Path=/cart-service/**

