server:
  port: 8081
  
spring:
  data:
    mongodb:
      uri: mongodb+srv://SV-Test:sayali@test.qx1qz.mongodb.net/Product  application:    name: PRODUCT-SERVICE
  servlet:    multipart:      enabled: true
           file-size-threshold: 2KB      max-file-size: 200MB        